### ISSUE TITLE
Admission and History form: Sorry, form save failed: Index 0 requested, with a size of 0

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#177] opened 2015-12-07 18:17 UTC
Trying to save admissions form, getting toast “Sorry, form save failed: Index 0 requested, with a size of 0”
(on build 880 connected to dev)

Anthropometrics form and Intensive Observations form work.

**Comment by llvasconcellos** [comment] 2015-12-15 10:26
Could not reproduce the error.

**Comment by capnfabs** [comment] 2016-01-04 03:10
Closing - @llvasconcellos couldn't repro, we'll reopen if we see it again. @dancunningham, if you spot this again, please take a bug report and include a copy of the server profile if possible. Thanks!

**Comment by dancunningham** [comment] 2016-01-19 14:52
This is the same as #218

**Comment by capnfabs** [comment] 2016-01-21 01:24
Ok. Closing again, we'll track this in https://github.com/projectbuendia/client/issues/218

**Comment by dancunningham** [comment] 2016-01-27 15:33
This just happened on Male's tablet

**Comment by capnfabs** [comment] 2016-01-27 19:11
Yeah I've seen it a few times too.

**Comment by dancunningham** [comment] 2016-01-28 12:43
Ivan just got this on 1st assessment form of profile v111 (profile file in profiles github repo)

**Comment by capnfabs** [comment] 2016-02-01 15:41
Ok, here's what's going on:

ODK attempts to retrieve the form definition using this URI:

```
content://org.projectbuendia.client.dev.odk.collect.android.provider.odk.forms/forms/31
```

But that form doesn't exist, and the actual form ID is #204:

<img width="543" alt="screen shot 2016-02-01 at 3 21 33 pm" src="https://cloud.githubusercontent.com/assets/1336508/12721392/847a465e-c8f7-11e5-8fd3-35b660b03136.png">

My current suspicion: The form IDs change on every sync, because all the forms get deleted from the ODK database and re-inserted. Looking for evidence now.

**Comment by capnfabs** [comment] 2016-02-01 16:41
That `_ID` field is never explicitly set, and is defined as `INTEGER PRIMARY KEY`, which means that it automatically becomes the [auto-incrementing `rowid`](https://www.sqlite.org/lang_createtable.html#rowid). When forms are `INSERT OR REPLACE`d in the database, ODK does this as an atomic delete and insert in a single transaction.

After a few syncs, here's what happens:

<img width="572" alt="screen shot 2016-02-01 at 4 40 42 pm" src="https://cloud.githubusercontent.com/assets/1336508/12723749/a409ca66-c902-11e5-92cc-c1d9b88868e1.png">

Observe that the ID has changed.

**Closed as completed** 2016-02-01 17:46 UTC
Labels: bug, P0

**Comment by llvasconcellos** [comment] 2016-02-11 17:25
Nice catch!
