### ISSUE TITLE
Submitting form gives "Index 0 requested" error

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#360] opened 2019-06-28 18:47 UTC
App version: (the number after "Buendia" on the starting screen)
Screen or dialog:

#### Steps to replicate the problem

This one is not always reproducible. Sometimes the form gets into a strange state where valid form data is not submitted. 

1. Enter an observation
2. Fill all the data
3. Save 

#### Actual behaviour
Error banner something about index 0

#### Expected behaviour
The form should have saved. 

#### Notes
Related to #329 

I think better validation errors would help to narrow down when this bug is happening - https://github.com/projectbuendia/client/issues/316

**Comment by saratheneale** [comment] 2019-07-03 23:28
I'm still running into this. There doesn't seem to be record of it in the log. @zestyping I'd really like some ideas on how to troubleshoot this more. I think better form validation errors will help a lot. 

Nonetheless here's the log. I pressed the button and got the error at around 16:18 several times. There's no timestamps for around that time. 

```
07-03 15:58:58.461  4957 16664 D CapturePreview: save result :  path : /storage/emulated/0/Android/data/com.sec.android.app.launcher/cache/homescreenPreview.png
07-03 15:59:43.017  2954 17006 D NetworkMonitor/NetworkAgentInfo [WIFI () - 639]: PROBE_HTTP http://connectivitycheck.gstatic.com/generate_204 time=60ms ret=204 request={Connection=[close], User-Agent=[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.32 Safari/537.36]} headers={null=[HTTP/1.1 204 No Content], Connection=[close], Content-Length=[0], Date=[Wed, 03 Jul 2019 22:59:38 GMT], X-Android-Received-Millis=[1562194783015], X-Android-Response-Source=[NETWORK 204], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1562194782987]}
07-03 15:59:43.081  2954 17005 D NetworkMonitor/NetworkAgentInfo [WIFI () - 639]: PROBE_HTTPS https://www.google.com/generate_204 time=123ms ret=204 request={Connection=[close], User-Agent=[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.32 Safari/537.36]} headers={null=[HTTP/1.1 204 No Content], Alt-Svc=[quic=":443"; ma=2592000; v="46,43,39"], Connection=[close], Content-Length=[0], Date=[Wed, 03 Jul 2019 22:59:38 GMT], X-Android-Received-Millis=[1562194783079], X-Android-Response-Source=[NETWORK 204], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1562194783046]}
07-03 15:59:43.517 17021 17049 I Finsky  : [5231] dgq.aR(9): Disable SystemUpdateActivity, because Android is lower than Q
07-03 16:00:15.086  2696 18561 E OMXNodeInstance: getConfig(0xf4f23c00:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
07-03 16:00:25.441 18068 18142 D skia    : --- SkAndroidCodec::NewFromStream returned null
07-03 16:00:25.452 18068 18142 D skia    : --- SkAndroidCodec::NewFromStream returned null
07-03 16:00:25.457 18068 18142 D skia    : --- SkAndroidCodec::NewFromStream returned null
07-03 16:00:27.751 18391 18391 I AndroidMusic: Application start. Process=MAIN
07-03 16:00:27.919 18391 18391 D AndroidMusic: GMSCore installation verified
07-03 16:00:38.602 18267 18300 I cr_ui   : Using UI locale en, system locale: en (Android name: en)
07-03 16:01:13.795 17021 17076 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1456)
07-03 16:01:13.912 17021 17076 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1456)
07-03 16:01:26.786 17021 17051 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
07-03 16:01:26.804 17021 17051 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
07-03 16:01:26.818 17021 17051 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
07-03 16:01:26.852 17021 17051 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
07-03 16:05:02.448 19822 19822 I AndroidMusic: Application start. Process=MAIN
07-03 16:05:02.640 19822 19822 D AndroidMusic: GMSCore installation verified
07-03 16:05:03.038 19885 19916 D skia    : --- SkAndroidCodec::NewFromStream returned null
07-03 16:05:03.050 19885 19916 D skia    : --- SkAndroidCodec::NewFromStream returned null
07-03 16:05:03.052 19885 19916 D skia    : --- SkAndroidCodec::NewFromStream returned null
07-03 16:10:09.184 17021 20769 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
07-03 16:10:09.236 17021 20769 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
07-03 16:10:14.530 17021 20769 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
07-03 16:10:14.550 17021 20769 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
07-03 16:10:14.592 17021 20769 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
07-03 16:10:14.627 17021 20769 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
07-03 16:10:14.646 17021 20769 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
07-03 16:10:14.655 17021 20769 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
07-03 16:10:14.656 17021 20769 W ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.
```

**Comment by zestyping** [comment] 2019-07-25 09:21
This is a duplicate of #329.

**Closed as completed** 2019-07-25 09:21 UTC
Labels: bug, duplicate, needs-replication, testing-party
